# Generated by Django 5.2 on 2026-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        help_text="Номер дня (1-30)",
                        unique=True,
                        verbose_name="День курса",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Контент (Markdown)")),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Теги"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["day_number"],
            },
        ),
    ]
